# Numpy Topics 


In [22]:
import numpy as np 
np.__version__
#print(np.__version__)

'1.16.4'

In [30]:
arr=np.array(
  {
      1:'One',
      2:'Two'
  }

)
arr

array({1: 'One', 2: 'Two'}, dtype=object)

In [31]:
arr.ndim

0

In [56]:
arra1=np.array(
    
    [[1,2,3,4,5,6,7],
    [1,2,3,4,5,6,7],
    [1,2,3,4,5,6,7]
    
    ]

)
arra1.ndim

2

In [55]:
arra1.shape

(3, 7)

In [51]:
arra1.reshape(7,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 2],
       [3, 4, 5],
       [6, 7, 1],
       [2, 3, 4],
       [5, 6, 7]])

In [53]:
arra1[1,2]

3

In [49]:
arra1.size

21

In [48]:
arra1.dtype

dtype('int64')

In [76]:
x=np.array(((1,2,3),(2,)))
x.ndim

1

In [74]:
a=np.array((5,2,3))
b=np.array((1,2,3))
print(a*b)

x=np.array((1,2,3))
y=np.array(9)
x*y


# vector 
# matrix 
# scalar 

[5 4 9]


array([ 9, 18, 27])