In [1]:
import numpy as np

In [2]:
import numpy.matlib

In [13]:
numpy.matlib.empty((3,4),int)  # shape dtype and order 

matrix([[                   0,                    0,
                            0,                    0],
        [                   0,                    0,
                            0,                    0],
        [                   0,  4189038621173441375,
          2305843009213693952, -6917520234980431390]])

In [20]:
numpy.matlib.eye(9,8,5,int) # n m  k and dtype   

matrix([[0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]])

In [25]:
numpy.matlib.identity(4,int) # n m  k and dtype 

matrix([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1]])

In [29]:
numpy.matlib.ones((4,4),int)

matrix([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])