In [ ]:
# # scalar vector matrix tensor 

# [1]

# [1,2,3]---> direction 
# [1]
# [2]
# [3]


# rows * cols 
# [1 2]
# [3 4]


# # deep learning - tensorflow - google - AI / DS 

In [ ]:
# 2014 - toy - 200 
# 2015 - toy -300 

# 202 - toy - ? 

# numpy scipy pandas and matplotlib 

In [6]:
import numpy as np 
price=np.array([1500,1800,1200,1300])
price
price.max()
price.mean()
price.min()
price.sum()

5800

In [12]:
np.linspace(1,10,6,dtype=int)

array([ 1,  2,  4,  6,  8, 10])

In [20]:
sample=np.array(
(5,6,7,8,0)  # 1 row and 5 cols 
)

sample.shape

s1=sample.reshape(5,1)
s1

array([[5],
       [6],
       [7],
       [8],
       [0]])

In [29]:
# assignment 1 

person=np.array(
{
    'name':'John',
    'age':45,
    'location':'NY'
})

person

array({'name': 'John', 'age': 45, 'location': 'NY'}, dtype=object)

In [25]:
population=np.array(
[20,40,60,80,100,120,150]  # 0 , n-1 n- length of list
)
population[2]

60

In [37]:
rc=np.array(
([1,2,30],
    
[10,15,14],
    
[2,3,4]
)
    
)
rc.max(axis=1)

rc.max(axis=0)

rc.sum(axis=0)

np.sqrt(rc)
np.std(rc)

8.981462390204987

In [43]:
np.ones((5,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [45]:
np.zeros((5,5),dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [47]:
#np.twos((5,5))

In [51]:
np.random.randn(5,2) # rand - to generate postive random values

array([[-1.09356471,  0.09277125],
       [ 1.17516699, -0.18509168],
       [-0.61472737, -0.24936354],
       [ 0.68936268,  1.08075797],
       [-0.02407016,  1.50501235]])

In [56]:
np.random.randint(8,size=100)

array([5, 1, 7, 0, 2, 7, 7, 3, 1, 0, 4, 3, 3, 3, 3, 2, 7, 4, 2, 2, 2, 6,
       3, 5, 1, 6, 5, 5, 0, 3, 5, 3, 0, 1, 0, 3, 1, 3, 3, 3, 6, 3, 1, 1,
       1, 1, 2, 2, 2, 3, 7, 7, 7, 1, 3, 1, 7, 3, 4, 5, 7, 0, 4, 5, 5, 5,
       0, 5, 3, 0, 0, 1, 6, 5, 6, 4, 5, 7, 5, 1, 5, 4, 0, 2, 0, 3, 6, 1,
       4, 3, 0, 1, 3, 7, 2, 5, 1, 5, 6, 3])

In [58]:
np.random.random_integers(3)

/Users/SRIRAMAPADMAPRABHA/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 3 + 1) instead
  """Entry point for launching an IPython kernel.


3

In [62]:
print(np.random.random_sample())
int(np.random.random_sample())

0.12978123938757147


0